// Stress tests for WaveRunner SessionManager and DSP pipeline.
//
// Exercises internals hard to find crashes, panics, data corruption,
// and deadlocks under adversarial conditions. Each test is independent
// and uses ReplayDevice (no hardware required).
//
// FINDINGS:
// - BUG FOUND (Test 13b): Event::AnnotationAdded uses blocking evt_tx.send()
//   in manager.rs. When many AddAnnotation commands are sent, the event
//   channel (bounded 256) fills up, blocking the processing thread. This
//   prevents command consumption, creating a deadlock when the command
//   channel (bounded 64) is also full. Same pattern affects any blocking
//   send event generated by a command (Status events from SetGain, Tune,
//   EnableDecoder, etc).
//
// Run with: cargo test -p wavecore --test stress_test -- --nocapture

use std::f32::consts::PI;
use std::io::Write;
use std::path::PathBuf;
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::time::{Duration, Instant};

use wavecore::analysis;
use wavecore::dsp::decoder::DecoderRegistry;
use wavecore::dsp::decoders;
use wavecore::hardware::GainMode;
use wavecore::session::manager::SessionManager;
use wavecore::session::replay::ReplayDevice;
use wavecore::session::{Command, Event, RecordFormat, SessionConfig, SessionStats};

// ============================================================================
// Helpers
// ============================================================================

/// Generate a cf32 file containing a synthetic multi-tone signal.
/// Returns (path, sample_count).
fn generate_test_cf32(tag: &str, sample_rate: f64, duration_secs: f64) -> (PathBuf, usize) {
    let num_samples = (sample_rate * duration_secs) as usize;
    let path = PathBuf::from(format!(
        "/tmp/waverunner_stress_{tag}_{}.cf32",
        std::process::id()
    ));
    let mut file = std::fs::File::create(&path).expect("create test cf32 file");

    // Multi-tone signal: 3 tones at different offsets
    let freqs = [50_000.0f32, -75_000.0, 120_000.0];
    for i in 0..num_samples {
        let t = i as f32 / sample_rate as f32;
        let mut re = 0.0f32;
        let mut im = 0.0f32;
        for &f in &freqs {
            let phase = 2.0 * PI * f * t;
            re += phase.cos() * 0.1;
            im += phase.sin() * 0.1;
        }
        // Add some pseudo-noise
        let noise = (
            (i as f32 * 1.618033).sin() * 0.01,
            (i as f32 * std::f32::consts::E).cos() * 0.01,
        );
        re += noise.0;
        im += noise.1;
        file.write_all(&re.to_le_bytes()).unwrap();
        file.write_all(&im.to_le_bytes()).unwrap();
    }
    file.flush().unwrap();
    (path, num_samples)
}

/// Create a minimal session config.
fn make_config(sample_rate: f64, fft_size: usize) -> SessionConfig {
    SessionConfig {
        schema_version: 1,
        device_index: 0,
        frequency: 100e6,
        sample_rate,
        gain: GainMode::Auto,
        ppm: 0,
        fft_size,
        pfa: 1e-4,
    }
}

/// Create a fresh decoder registry with all decoders registered.
fn full_registry() -> DecoderRegistry {
    let mut reg = DecoderRegistry::new();
    decoders::register_all(&mut reg);
    reg
}

/// Drain events with timeout, returning final SessionStats.
fn drain_events(
    session: &SessionManager,
    event_rx: &crossbeam_channel::Receiver<Event>,
    timeout_secs: u64,
) -> Option<SessionStats> {
    let mut last_stats: Option<SessionStats> = None;
    let mut error_count = 0u64;
    let deadline = Instant::now() + Duration::from_secs(timeout_secs);

    loop {
        if Instant::now() > deadline {
            eprintln!("  [TIMEOUT] after {}s", timeout_secs);
            break;
        }
        match event_rx.recv_timeout(Duration::from_millis(300)) {
            Ok(Event::Stats(stats)) => {
                last_stats = Some(stats);
            }
            Ok(Event::Error(e)) => {
                error_count += 1;
                if error_count <= 5 {
                    eprintln!("  [ERROR] {}", e);
                }
            }
            Ok(_) => {}
            Err(crossbeam_channel::RecvTimeoutError::Timeout) => {
                if !session.is_running() {
                    break;
                }
            }
            Err(crossbeam_channel::RecvTimeoutError::Disconnected) => break,
        }
    }
    if error_count > 5 {
        eprintln!("  ... and {} more errors", error_count - 5);
    }
    last_stats
}

/// Spawn a background thread that continuously drains events from the receiver.
/// Returns a handle and an Arc containing the latest stats.
/// Set the stop flag to false to stop draining.
fn spawn_event_drainer(
    event_rx: crossbeam_channel::Receiver<Event>,
    stop: Arc<AtomicBool>,
) -> (
    std::thread::JoinHandle<()>,
    Arc<std::sync::Mutex<Option<SessionStats>>>,
) {
    let stats = Arc::new(std::sync::Mutex::new(None::<SessionStats>));
    let stats_clone = Arc::clone(&stats);
    let handle = std::thread::Builder::new()
        .name("event-drainer".to_string())
        .spawn(move || {
            while !stop.load(Ordering::Relaxed) {
                match event_rx.recv_timeout(Duration::from_millis(50)) {
                    Ok(Event::Stats(s)) => {
                        *stats_clone.lock().unwrap() = Some(s);
                    }
                    Ok(_) => {}
                    Err(_) => {}
                }
            }
            // Final drain after stop
            while let Ok(ev) = event_rx.try_recv() {
                if let Event::Stats(s) = ev {
                    *stats_clone.lock().unwrap() = Some(s);
                }
            }
        })
        .expect("spawn drainer thread");
    (handle, stats)
}

// ============================================================================
// Test 1: Rapid frequency hopping
// ============================================================================

#[test]
fn stress_rapid_frequency_hopping() {
    eprintln!("\n=== Test 1: Rapid frequency hopping ===");
    let sample_rate = 2_048_000.0;
    let (path, _) = generate_test_cf32("freqhop", sample_rate, 2.0);

    let device = ReplayDevice::open(&path, sample_rate).expect("open replay device");
    let config = make_config(sample_rate, 2048);

    let (session, event_rx) =
        SessionManager::new_with_device(config, device, full_registry()).expect("start session");

    // Drain events in background to prevent backpressure deadlock
    // (Tune commands produce Status events via blocking send)
    let stop = Arc::new(AtomicBool::new(false));
    let (drainer, drainer_stats) = spawn_event_drainer(event_rx, Arc::clone(&stop));

    // Slam 500 frequency changes in rapid succession
    for i in 0..500u64 {
        let freq = 88e6 + (i as f64 * 0.2e6);
        if session.send(Command::Tune(freq)).is_err() {
            eprintln!("  Command channel closed after {} tune commands", i);
            break;
        }
    }
    eprintln!("  Sent 500 tune commands");

    // Wait for session to finish
    let deadline = Instant::now() + Duration::from_secs(15);
    while session.is_running() && Instant::now() < deadline {
        std::thread::sleep(Duration::from_millis(100));
    }

    stop.store(true, Ordering::Relaxed);
    session.shutdown();
    drainer.join().expect("drainer panicked");
    std::fs::remove_file(&path).ok();

    let stats = drainer_stats.lock().unwrap().clone();
    if let Some(stats) = stats {
        eprintln!(
            "  blocks_processed={}, blocks_dropped={}, events_dropped={}",
            stats.blocks_processed, stats.blocks_dropped, stats.events_dropped
        );
        assert!(
            stats.blocks_processed >= 1,
            "Expected at least 1 block processed"
        );
    }
    eprintln!("  PASSED: No panic, no deadlock");
}

// ============================================================================
// Test 2: All decoders simultaneously
// ============================================================================

#[test]
fn stress_all_decoders_simultaneously() {
    eprintln!("\n=== Test 2: All decoders simultaneously ===");
    let sample_rate = 2_048_000.0;
    let (path, _) = generate_test_cf32("alldec", sample_rate, 2.0);

    let device = ReplayDevice::open(&path, sample_rate).expect("open replay device");
    let config = make_config(sample_rate, 2048);

    let (session, event_rx) =
        SessionManager::new_with_device(config, device, full_registry()).expect("start session");

    // Enable every decoder that isn't rtl433 (which needs external binary)
    let decoder_names: Vec<&str> = wavecore::dsp::decoders::DECODER_NAMES
        .iter()
        .copied()
        .filter(|name| !name.starts_with("rtl433"))
        .collect();

    eprintln!(
        "  Enabling {} decoders: {:?}",
        decoder_names.len(),
        decoder_names
    );

    for name in &decoder_names {
        session
            .send(Command::EnableDecoder(name.to_string()))
            .expect("enable decoder");
    }

    let stats = drain_events(&session, &event_rx, 15);
    session.shutdown();
    std::fs::remove_file(&path).ok();

    if let Some(stats) = stats {
        eprintln!(
            "  blocks_processed={}, blocks_dropped={}, events_dropped={}",
            stats.blocks_processed, stats.blocks_dropped, stats.events_dropped
        );
        assert!(
            stats.blocks_processed >= 1,
            "Expected at least 1 block with all decoders"
        );
    }
    eprintln!("  PASSED: All decoders enabled without panic");
}

// ============================================================================
// Test 3: Rapid start/stop
// ============================================================================

#[test]
fn stress_rapid_start_stop() {
    eprintln!("\n=== Test 3: Rapid start/stop (20 cycles) ===");
    let sample_rate = 2_048_000.0;
    let (path, _) = generate_test_cf32("startstop", sample_rate, 0.5);

    for cycle in 0..20 {
        let device = ReplayDevice::open(&path, sample_rate).expect("open replay device");
        let config = make_config(sample_rate, 1024);

        let (session, event_rx) = SessionManager::new_with_device(config, device, full_registry())
            .expect("start session");

        // Let it run briefly
        std::thread::sleep(Duration::from_millis(50));

        // Drain a few events
        for _ in 0..10 {
            match event_rx.try_recv() {
                Ok(_) => {}
                Err(_) => break,
            }
        }

        session.shutdown();

        if cycle % 5 == 0 {
            eprintln!("  Cycle {}/20 complete", cycle + 1);
        }
    }

    std::fs::remove_file(&path).ok();
    eprintln!("  PASSED: 20 start/stop cycles without panic or deadlock");
}

// ============================================================================
// Test 4: Command flooding (with concurrent event drain)
// ============================================================================

#[test]
fn stress_command_flooding() {
    eprintln!("\n=== Test 4: Command flooding ===");
    let sample_rate = 2_048_000.0;
    let (path, _) = generate_test_cf32("cmdflood", sample_rate, 3.0);

    let device = ReplayDevice::open(&path, sample_rate).expect("open replay device");
    let config = make_config(sample_rate, 2048);

    let (session, event_rx) =
        SessionManager::new_with_device(config, device, full_registry()).expect("start session");

    let rec_path = PathBuf::from(format!(
        "/tmp/waverunner_stress_rec_{}.cf32",
        std::process::id()
    ));

    // MUST drain events concurrently: commands produce blocking Status events
    // which fill the event channel and deadlock if not drained.
    let stop = Arc::new(AtomicBool::new(false));
    let (drainer, drainer_stats) = spawn_event_drainer(event_rx, Arc::clone(&stop));

    // Fire every command type rapidly
    let mut sent = 0u64;
    for i in 0..50u64 {
        let cmds: Vec<Command> = vec![
            Command::Tune(88e6 + (i as f64 * 1e6)),
            Command::SetGain(if i % 2 == 0 {
                GainMode::Auto
            } else {
                GainMode::Manual(20.0 + i as f64)
            }),
            Command::SetSampleRate(if i % 3 == 0 { 1_024_000.0 } else { 2_048_000.0 }),
            Command::EnableDecoder("pocsag".to_string()),
            Command::DisableDecoder("pocsag".to_string()),
            Command::EnableDecoder("adsb".to_string()),
            Command::CaptureReference,
            Command::StartTracking,
            Command::RunAnalysis {
                id: i,
                request: analysis::AnalysisRequest::MeasureSignal(
                    analysis::measurement::MeasureConfig {
                        signal_center_bin: 512,
                        signal_width_bins: 100,
                        adjacent_width_bins: 50,
                        obw_threshold_db: 26.0,
                    },
                ),
            },
            Command::StopTracking,
            Command::AddAnnotation {
                kind: "note".to_string(),
                text: format!("stress annotation {i}"),
            },
        ];

        for cmd in cmds {
            if session.send(cmd).is_err() {
                eprintln!("  Command channel closed after {} commands", sent);
                break;
            }
            sent += 1;
        }
    }

    // Also try start/stop recording
    let _ = session.send(Command::StartRecord {
        path: rec_path.clone(),
        format: RecordFormat::RawCf32,
    });
    std::thread::sleep(Duration::from_millis(100));
    let _ = session.send(Command::StopRecord);

    eprintln!("  Sent {} commands total", sent);

    // Wait for session end
    let deadline = Instant::now() + Duration::from_secs(15);
    while session.is_running() && Instant::now() < deadline {
        std::thread::sleep(Duration::from_millis(100));
    }

    stop.store(true, Ordering::Relaxed);
    session.shutdown();
    drainer.join().expect("drainer panicked");
    std::fs::remove_file(&path).ok();
    std::fs::remove_file(&rec_path).ok();
    let mut sidecar = rec_path.clone();
    sidecar.set_extension("sigmf-meta");
    std::fs::remove_file(&sidecar).ok();

    let stats = drainer_stats.lock().unwrap().clone();
    if let Some(stats) = stats {
        eprintln!(
            "  blocks_processed={}, blocks_dropped={}, events_dropped={}",
            stats.blocks_processed, stats.blocks_dropped, stats.events_dropped
        );
    }
    eprintln!("  PASSED: Command flooding without panic or deadlock");
}

// ============================================================================
// Test 5: Large FFT sizes
// ============================================================================

#[test]
fn stress_large_fft_sizes() {
    eprintln!("\n=== Test 5: Large FFT sizes ===");
    let sample_rate = 2_048_000.0;

    let fft_sizes = [4096, 8192, 16384, 32768, 65536];

    for &fft_size in &fft_sizes {
        eprintln!("  Testing FFT size {}...", fft_size);

        let duration = 0.5;
        let tag = format!("fft{}", fft_size);
        let (path, _) = generate_test_cf32(&tag, sample_rate, duration);

        let device = ReplayDevice::open(&path, sample_rate).expect("open replay device");
        let config = make_config(sample_rate, fft_size);

        let (session, event_rx) = SessionManager::new_with_device(config, device, full_registry())
            .expect("start session");

        let stats = drain_events(&session, &event_rx, 15);
        session.shutdown();
        std::fs::remove_file(&path).ok();

        if let Some(stats) = stats {
            eprintln!(
                "    FFT {}: blocks_processed={}, blocks_dropped={}",
                fft_size, stats.blocks_processed, stats.blocks_dropped
            );
            assert!(
                stats.blocks_processed >= 1,
                "FFT size {} should process at least 1 block",
                fft_size
            );
        }
    }
    eprintln!("  PASSED: All large FFT sizes work");
}

// ============================================================================
// Test 6: Analysis under load
// ============================================================================

#[test]
fn stress_analysis_under_load() {
    eprintln!("\n=== Test 6: Analysis under load ===");
    let sample_rate = 2_048_000.0;
    let (path, _) = generate_test_cf32("analysis", sample_rate, 3.0);

    let device = ReplayDevice::open(&path, sample_rate).expect("open replay device");
    let config = make_config(sample_rate, 2048);

    let (session, event_rx) =
        SessionManager::new_with_device(config, device, full_registry()).expect("start session");

    // Enable a few decoders for extra load
    session
        .send(Command::EnableDecoder("pocsag".to_string()))
        .ok();
    session
        .send(Command::EnableDecoder("adsb".to_string()))
        .ok();
    session
        .send(Command::EnableDecoder("aprs".to_string()))
        .ok();
    session.send(Command::StartTracking).ok();
    session.send(Command::CaptureReference).ok();

    // AnalysisResult events use blocking send, so drain concurrently
    let stop = Arc::new(AtomicBool::new(false));
    let analysis_results = Arc::new(AtomicU64::new(0));
    let stats_holder = Arc::new(std::sync::Mutex::new(None::<SessionStats>));

    let ar = Arc::clone(&analysis_results);
    let sh = Arc::clone(&stats_holder);
    let st = Arc::clone(&stop);
    let drainer = std::thread::Builder::new()
        .name("analysis-drainer".to_string())
        .spawn(move || {
            while !st.load(Ordering::Relaxed) {
                match event_rx.recv_timeout(Duration::from_millis(50)) {
                    Ok(Event::Stats(s)) => {
                        *sh.lock().unwrap() = Some(s);
                    }
                    Ok(Event::AnalysisResult { .. }) => {
                        ar.fetch_add(1, Ordering::Relaxed);
                    }
                    Ok(_) => {}
                    Err(_) => {}
                }
            }
            // Final drain
            while let Ok(ev) = event_rx.try_recv() {
                match ev {
                    Event::Stats(s) => {
                        *sh.lock().unwrap() = Some(s);
                    }
                    Event::AnalysisResult { .. } => {
                        ar.fetch_add(1, Ordering::Relaxed);
                    }
                    _ => {}
                }
            }
        })
        .expect("spawn analysis drainer");

    // Spam analysis requests while pipeline is running
    let mut analysis_count = 0u64;
    for i in 0..100u64 {
        let request = match i % 5 {
            0 => analysis::AnalysisRequest::MeasureSignal(analysis::measurement::MeasureConfig {
                signal_center_bin: 1024,
                signal_width_bins: 200,
                adjacent_width_bins: 100,
                obw_threshold_db: 26.0,
            }),
            1 => analysis::AnalysisRequest::AnalyzeBurst(analysis::burst::BurstConfig {
                threshold_db: 6.0,
                min_burst_samples: 100,
                sample_rate,
            }),
            2 => analysis::AnalysisRequest::EstimateModulation(
                analysis::modulation::ModulationConfig {
                    sample_rate,
                    fft_size: 1024,
                },
            ),
            3 => analysis::AnalysisRequest::CompareSpectra,
            _ => analysis::AnalysisRequest::TrackingSnapshot,
        };

        if session
            .send(Command::RunAnalysis {
                id: i + 1000,
                request,
            })
            .is_err()
        {
            break;
        }
        analysis_count += 1;
    }

    eprintln!("  Sent {} analysis requests", analysis_count);

    // Wait for session to finish
    let deadline = Instant::now() + Duration::from_secs(15);
    while session.is_running() && Instant::now() < deadline {
        std::thread::sleep(Duration::from_millis(100));
    }

    stop.store(true, Ordering::Relaxed);
    session.shutdown();
    drainer.join().expect("drainer panicked");
    std::fs::remove_file(&path).ok();

    let ar_count = analysis_results.load(Ordering::Relaxed);
    eprintln!("  Received {} analysis results", ar_count);
    let stats = stats_holder.lock().unwrap().clone();
    if let Some(stats) = stats {
        eprintln!(
            "  blocks_processed={}, blocks_dropped={}, events_dropped={}",
            stats.blocks_processed, stats.blocks_dropped, stats.events_dropped
        );
    }
    eprintln!("  PASSED: Analysis under load without panic");
}

// ============================================================================
// Test 7: Event drain stress (let channel fill up, then drain)
// ============================================================================

#[test]
fn stress_event_drain() {
    eprintln!("\n=== Test 7: Event drain stress ===");
    let sample_rate = 2_048_000.0;
    let (path, _) = generate_test_cf32("evtdrain", sample_rate, 3.0);

    let device = ReplayDevice::open(&path, sample_rate).expect("open replay device");
    let config = make_config(sample_rate, 2048);

    let (session, event_rx) =
        SessionManager::new_with_device(config, device, full_registry()).expect("start session");

    // Enable decoders for extra event generation
    session
        .send(Command::EnableDecoder("pocsag".to_string()))
        .ok();
    session
        .send(Command::EnableDecoder("adsb".to_string()))
        .ok();

    // Don't drain events for 2 seconds -- let the load shedder and
    // try_send_event kick in
    eprintln!("  Sleeping 2s without draining events (letting channel fill)...");
    std::thread::sleep(Duration::from_secs(2));

    // Now drain everything in a burst
    let mut event_count = 0u64;
    let mut stats_count = 0u64;
    let mut last_stats: Option<SessionStats> = None;

    loop {
        match event_rx.try_recv() {
            Ok(Event::Stats(stats)) => {
                stats_count += 1;
                last_stats = Some(stats);
                event_count += 1;
            }
            Ok(_) => {
                event_count += 1;
            }
            Err(_) => break,
        }
    }

    eprintln!(
        "  Burst-drained {} events ({} stats)",
        event_count, stats_count
    );

    // Continue draining normally until session ends
    let final_stats = drain_events(&session, &event_rx, 10);
    session.shutdown();
    std::fs::remove_file(&path).ok();

    let stats = final_stats.or(last_stats);
    if let Some(stats) = stats {
        eprintln!(
            "  blocks_processed={}, blocks_dropped={}, events_dropped={}",
            stats.blocks_processed, stats.blocks_dropped, stats.events_dropped
        );
        assert!(
            stats.blocks_processed >= 1,
            "Expected at least 1 block processed"
        );
    }
    eprintln!("  PASSED: Event drain stress without panic or deadlock");
}

// ============================================================================
// Test 8: Multi-threaded interaction
// ============================================================================

#[test]
fn stress_multi_threaded_interaction() {
    eprintln!("\n=== Test 8: Multi-threaded event consumption ===");
    let sample_rate = 2_048_000.0;
    let (path, _) = generate_test_cf32("multithread", sample_rate, 3.0);

    let device = ReplayDevice::open(&path, sample_rate).expect("open replay device");
    let config = make_config(sample_rate, 2048);

    let (session, event_rx) =
        SessionManager::new_with_device(config, device, full_registry()).expect("start session");

    let cmd_sender = session.cmd_sender();
    let running = Arc::new(AtomicBool::new(true));
    let total_commands = Arc::new(AtomicU64::new(0));

    // Drain events in background (commands produce blocking Status events)
    let stop_drainer = Arc::new(AtomicBool::new(false));
    let (drainer, drainer_stats) = spawn_event_drainer(event_rx, Arc::clone(&stop_drainer));

    // Spawn 4 threads that each send commands concurrently
    let mut handles = Vec::new();

    for thread_id in 0..4usize {
        let sender = cmd_sender.clone();
        let running = Arc::clone(&running);
        let total = Arc::clone(&total_commands);

        let handle = std::thread::Builder::new()
            .name(format!("stress-cmd-{}", thread_id))
            .spawn(move || {
                let mut i = 0u64;
                while running.load(Ordering::Relaxed) {
                    let cmd = match (thread_id + i as usize) % 6 {
                        0 => Command::Tune(88e6 + (i as f64 * 0.1e6)),
                        1 => Command::SetGain(GainMode::Manual(10.0 + i as f64 % 40.0)),
                        2 => Command::EnableDecoder("pocsag".to_string()),
                        3 => Command::DisableDecoder("pocsag".to_string()),
                        4 => Command::CaptureReference,
                        _ => Command::AddAnnotation {
                            kind: "tag".to_string(),
                            text: format!("thread {} iter {}", thread_id, i),
                        },
                    };

                    if sender.send(cmd).is_err() {
                        break;
                    }
                    total.fetch_add(1, Ordering::Relaxed);
                    i += 1;

                    // Tiny yield to avoid completely monopolizing CPU
                    if i % 50 == 0 {
                        std::thread::yield_now();
                    }
                }
            })
            .expect("spawn command thread");

        handles.push(handle);
    }

    // Let the chaos run for 2 seconds
    std::thread::sleep(Duration::from_secs(2));

    // Signal command threads to stop
    running.store(false, Ordering::Relaxed);

    for handle in handles {
        handle.join().expect("command thread panicked!");
    }

    let total_sent = total_commands.load(Ordering::Relaxed);
    eprintln!("  {} total commands sent from 4 threads", total_sent);

    // Wait for session end
    let deadline = Instant::now() + Duration::from_secs(15);
    while session.is_running() && Instant::now() < deadline {
        std::thread::sleep(Duration::from_millis(100));
    }

    stop_drainer.store(true, Ordering::Relaxed);
    session.shutdown();
    drainer.join().expect("drainer panicked");
    std::fs::remove_file(&path).ok();

    let stats = drainer_stats.lock().unwrap().clone();
    if let Some(stats) = stats {
        eprintln!(
            "  blocks_processed={}, blocks_dropped={}, events_dropped={}",
            stats.blocks_processed, stats.blocks_dropped, stats.events_dropped
        );
    }
    eprintln!("  PASSED: Multi-threaded interaction without panic or deadlock");
}

// ============================================================================
// Test 9: Decoder enable/disable thrashing
// ============================================================================

#[test]
fn stress_decoder_thrashing() {
    eprintln!("\n=== Test 9: Decoder enable/disable thrashing ===");
    let sample_rate = 2_048_000.0;
    let (path, _) = generate_test_cf32("decthrash", sample_rate, 3.0);

    let device = ReplayDevice::open(&path, sample_rate).expect("open replay device");
    let config = make_config(sample_rate, 2048);

    let (session, event_rx) =
        SessionManager::new_with_device(config, device, full_registry()).expect("start session");

    let decoder_names: Vec<&str> = wavecore::dsp::decoders::DECODER_NAMES
        .iter()
        .copied()
        .filter(|name| !name.starts_with("rtl433"))
        .collect();

    // Drain events in background (EnableDecoder/DisableDecoder produce Status events)
    let stop = Arc::new(AtomicBool::new(false));
    let (drainer, drainer_stats) = spawn_event_drainer(event_rx, Arc::clone(&stop));

    // Rapidly enable and disable decoders
    for cycle in 0..30 {
        for name in &decoder_names {
            if cycle % 2 == 0 {
                let _ = session.send(Command::EnableDecoder(name.to_string()));
            } else {
                let _ = session.send(Command::DisableDecoder(name.to_string()));
            }
        }
    }

    eprintln!(
        "  Sent {} enable/disable commands",
        30 * decoder_names.len()
    );

    // Wait for session end
    let deadline = Instant::now() + Duration::from_secs(15);
    while session.is_running() && Instant::now() < deadline {
        std::thread::sleep(Duration::from_millis(100));
    }

    stop.store(true, Ordering::Relaxed);
    session.shutdown();
    drainer.join().expect("drainer panicked");
    std::fs::remove_file(&path).ok();

    let stats = drainer_stats.lock().unwrap().clone();
    if let Some(stats) = stats {
        eprintln!(
            "  blocks_processed={}, blocks_dropped={}, events_dropped={}",
            stats.blocks_processed, stats.blocks_dropped, stats.events_dropped
        );
    }
    eprintln!("  PASSED: Decoder thrashing without panic or deadlock");
}

// ============================================================================
// Test 10: Recording start/stop under load
// ============================================================================

#[test]
fn stress_recording_start_stop() {
    eprintln!("\n=== Test 10: Recording start/stop under load ===");
    let sample_rate = 2_048_000.0;
    let (path, _) = generate_test_cf32("recstress", sample_rate, 3.0);

    let device = ReplayDevice::open(&path, sample_rate).expect("open replay device");
    let config = make_config(sample_rate, 2048);

    let (session, event_rx) =
        SessionManager::new_with_device(config, device, full_registry()).expect("start session");

    let rec_dir = PathBuf::from(format!(
        "/tmp/waverunner_stress_recs_{}",
        std::process::id()
    ));
    std::fs::create_dir_all(&rec_dir).ok();

    // RecordingStarted/Stopped events use blocking send, drain concurrently
    let stop = Arc::new(AtomicBool::new(false));
    let (drainer, drainer_stats) = spawn_event_drainer(event_rx, Arc::clone(&stop));

    // Rapidly start/stop recordings in different formats
    for i in 0..20 {
        let (fname, format) = match i % 3 {
            0 => (format!("rec_{}.cf32", i), RecordFormat::RawCf32),
            1 => (format!("rec_{}.wav", i), RecordFormat::Wav),
            _ => (format!("rec_{}.sigmf-data", i), RecordFormat::SigMf),
        };

        let rec_path = rec_dir.join(fname);
        let _ = session.send(Command::StartRecord {
            path: rec_path,
            format,
        });

        // Brief recording
        std::thread::sleep(Duration::from_millis(20));

        let _ = session.send(Command::StopRecord);
    }

    eprintln!("  Cycled through 20 recording start/stop pairs");

    let deadline = Instant::now() + Duration::from_secs(15);
    while session.is_running() && Instant::now() < deadline {
        std::thread::sleep(Duration::from_millis(100));
    }

    stop.store(true, Ordering::Relaxed);
    session.shutdown();
    drainer.join().expect("drainer panicked");
    std::fs::remove_file(&path).ok();

    // Clean up recordings
    std::fs::remove_dir_all(&rec_dir).ok();

    let stats = drainer_stats.lock().unwrap().clone();
    if let Some(stats) = stats {
        eprintln!(
            "  blocks_processed={}, blocks_dropped={}",
            stats.blocks_processed, stats.blocks_dropped
        );
    }
    eprintln!("  PASSED: Recording start/stop under load without panic");
}

// ============================================================================
// Test 11: Edge case -- zero-length / tiny signals
// ============================================================================

#[test]
fn stress_tiny_signal_file() {
    eprintln!("\n=== Test 11: Tiny signal file (minimal samples) ===");
    let sample_rate = 2_048_000.0;

    // Create a file with just 64 samples (way less than one block)
    let (path, _) = generate_test_cf32("tiny", sample_rate, 64.0 / sample_rate);

    let device = ReplayDevice::open(&path, sample_rate).expect("open replay device");
    let config = make_config(sample_rate, 1024);

    let (session, event_rx) =
        SessionManager::new_with_device(config, device, full_registry()).expect("start session");

    // Enable decoders on this tiny signal
    session
        .send(Command::EnableDecoder("pocsag".to_string()))
        .ok();
    session
        .send(Command::EnableDecoder("adsb".to_string()))
        .ok();
    session.send(Command::StartTracking).ok();
    session.send(Command::CaptureReference).ok();

    let stats = drain_events(&session, &event_rx, 10);
    session.shutdown();
    std::fs::remove_file(&path).ok();

    if let Some(stats) = stats {
        eprintln!(
            "  blocks_processed={}, blocks_dropped={}",
            stats.blocks_processed, stats.blocks_dropped
        );
    }
    eprintln!("  PASSED: Tiny signal without panic");
}

// ============================================================================
// Test 12: Extreme parameter values
// ============================================================================

#[test]
fn stress_extreme_parameters() {
    eprintln!("\n=== Test 12: Extreme parameter values ===");
    let sample_rate = 2_048_000.0;
    let (path, _) = generate_test_cf32("extreme", sample_rate, 1.5);

    let device = ReplayDevice::open(&path, sample_rate).expect("open replay device");
    let config = make_config(sample_rate, 2048);

    let (session, event_rx) =
        SessionManager::new_with_device(config, device, full_registry()).expect("start session");

    // Drain concurrently (Status events from Tune/SetGain use blocking send)
    let stop = Arc::new(AtomicBool::new(false));
    let (drainer, drainer_stats) = spawn_event_drainer(event_rx, Arc::clone(&stop));

    // Extreme frequencies
    let _ = session.send(Command::Tune(0.0));
    let _ = session.send(Command::Tune(f64::MAX / 2.0));
    let _ = session.send(Command::Tune(1.0));
    let _ = session.send(Command::Tune(6e9));

    // Extreme gains
    let _ = session.send(Command::SetGain(GainMode::Manual(0.0)));
    let _ = session.send(Command::SetGain(GainMode::Manual(-100.0)));
    let _ = session.send(Command::SetGain(GainMode::Manual(1000.0)));
    let _ = session.send(Command::SetGain(GainMode::Auto));

    // Extreme sample rates
    let _ = session.send(Command::SetSampleRate(1.0));
    let _ = session.send(Command::SetSampleRate(100_000_000.0));
    let _ = session.send(Command::SetSampleRate(sample_rate)); // restore

    // Analysis with edge-case parameters
    let _ = session.send(Command::RunAnalysis {
        id: 9001,
        request: analysis::AnalysisRequest::MeasureSignal(analysis::measurement::MeasureConfig {
            signal_center_bin: 0,
            signal_width_bins: 0,
            adjacent_width_bins: 0,
            obw_threshold_db: 0.0,
        }),
    });
    let _ = session.send(Command::RunAnalysis {
        id: 9002,
        request: analysis::AnalysisRequest::MeasureSignal(analysis::measurement::MeasureConfig {
            signal_center_bin: usize::MAX,
            signal_width_bins: usize::MAX,
            adjacent_width_bins: usize::MAX,
            obw_threshold_db: f32::MAX,
        }),
    });
    let _ = session.send(Command::RunAnalysis {
        id: 9003,
        request: analysis::AnalysisRequest::AnalyzeBurst(analysis::burst::BurstConfig {
            threshold_db: 0.0,
            min_burst_samples: 0,
            sample_rate: 0.0,
        }),
    });
    let _ = session.send(Command::RunAnalysis {
        id: 9004,
        request: analysis::AnalysisRequest::EstimateModulation(
            analysis::modulation::ModulationConfig {
                sample_rate: 0.0,
                fft_size: 0,
            },
        ),
    });

    let deadline = Instant::now() + Duration::from_secs(15);
    while session.is_running() && Instant::now() < deadline {
        std::thread::sleep(Duration::from_millis(100));
    }

    stop.store(true, Ordering::Relaxed);
    session.shutdown();
    drainer.join().expect("drainer panicked");
    std::fs::remove_file(&path).ok();

    let stats = drainer_stats.lock().unwrap().clone();
    if let Some(stats) = stats {
        eprintln!(
            "  blocks_processed={}, blocks_dropped={}",
            stats.blocks_processed, stats.blocks_dropped
        );
    }
    eprintln!("  PASSED: Extreme parameters without panic");
}

// ============================================================================
// Test 13a: Timeline annotation spam (with concurrent drain -- works around bug)
// ============================================================================

#[test]
fn stress_annotation_spam() {
    eprintln!("\n=== Test 13a: Timeline annotation spam (with drain) ===");
    let sample_rate = 2_048_000.0;
    let (path, _) = generate_test_cf32("annot", sample_rate, 2.0);

    let device = ReplayDevice::open(&path, sample_rate).expect("open replay device");
    let config = make_config(sample_rate, 2048);

    let (session, event_rx) =
        SessionManager::new_with_device(config, device, full_registry()).expect("start session");

    // MUST drain events concurrently: AnnotationAdded uses blocking send().
    // Without draining, 256+ annotations will deadlock (see Test 13b).
    let stop = Arc::new(AtomicBool::new(false));
    let (drainer, drainer_stats) = spawn_event_drainer(event_rx, Arc::clone(&stop));

    // Spam 1000 annotations
    for i in 0..1000u64 {
        let _ = session.send(Command::AddAnnotation {
            kind: match i % 3 {
                0 => "bookmark".to_string(),
                1 => "note".to_string(),
                _ => "tag".to_string(),
            },
            text: format!(
                "Stress annotation #{}: {}",
                i,
                "x".repeat((i % 200) as usize)
            ),
        });
    }

    eprintln!("  Sent 1000 annotations");

    // Export timeline
    let timeline_path = PathBuf::from(format!(
        "/tmp/waverunner_stress_timeline_{}.json",
        std::process::id()
    ));
    let _ = session.send(Command::ExportTimeline {
        path: timeline_path.clone(),
        format: wavecore::session::TimelineExportFormat::Json,
    });

    let deadline = Instant::now() + Duration::from_secs(15);
    while session.is_running() && Instant::now() < deadline {
        std::thread::sleep(Duration::from_millis(100));
    }

    stop.store(true, Ordering::Relaxed);
    session.shutdown();
    drainer.join().expect("drainer panicked");
    std::fs::remove_file(&path).ok();
    std::fs::remove_file(&timeline_path).ok();

    let stats = drainer_stats.lock().unwrap().clone();
    if let Some(stats) = stats {
        eprintln!(
            "  blocks_processed={}, events_dropped={}",
            stats.blocks_processed, stats.events_dropped
        );
    }
    eprintln!("  PASSED: Annotation spam without panic");
}

// ============================================================================
// Test 13b: Annotation deadlock detection
//
// BUG: Event::AnnotationAdded uses blocking evt_tx.send() in manager.rs.
// When we send >256 AddAnnotation commands WITHOUT draining events, the
// event channel fills up, the processing thread blocks on send, the command
// channel fills up, and the caller blocks on command send. Deadlock.
//
// This test verifies the bug exists by checking for timeout. It uses a
// separate thread for command sending so we don't block the test harness.
//
// NOTE: We cannot call session.shutdown() after confirming a deadlock because
// shutdown() tries to join the processing thread (which is blocked on
// evt_tx.send()). Instead, we drain the event_rx to unblock the processing
// thread, then shut down normally.
// ============================================================================

#[test]
fn stress_annotation_deadlock_detection() {
    eprintln!("\n=== Test 13b: Annotation deadlock detection ===");
    eprintln!("  BUG: AnnotationAdded uses blocking send() -- testing for deadlock");
    let sample_rate = 2_048_000.0;
    let (path, _) = generate_test_cf32("annotdl", sample_rate, 5.0);

    let device = ReplayDevice::open(&path, sample_rate).expect("open replay device");
    let config = make_config(sample_rate, 2048);

    let (session, event_rx) =
        SessionManager::new_with_device(config, device, full_registry()).expect("start session");

    // Try to send 400 annotations WITHOUT draining events.
    // Command channel = 64 bounded, event channel = 256 bounded.
    // After ~256 annotations processed, event channel is full.
    // Processing thread blocks on send. Command channel fills to 64.
    // Total = ~320 before deadlock.
    let cmd_sender = session.cmd_sender();
    let sent_count = Arc::new(AtomicU64::new(0));
    let sent_clone = Arc::clone(&sent_count);
    let finished = Arc::new(AtomicBool::new(false));
    let finished_clone = Arc::clone(&finished);

    let sender_thread = std::thread::Builder::new()
        .name("annotation-sender".to_string())
        .spawn(move || {
            for i in 0..400u64 {
                if cmd_sender
                    .send(Command::AddAnnotation {
                        kind: "note".to_string(),
                        text: format!("annotation {i}"),
                    })
                    .is_err()
                {
                    break;
                }
                sent_clone.fetch_add(1, Ordering::Relaxed);
            }
            finished_clone.store(true, Ordering::Relaxed);
        })
        .expect("spawn sender");

    // Wait up to 5 seconds. If the sender doesn't finish, it's deadlocked.
    let deadline = Instant::now() + Duration::from_secs(5);
    while !finished.load(Ordering::Relaxed) && Instant::now() < deadline {
        std::thread::sleep(Duration::from_millis(50));
    }

    let sent = sent_count.load(Ordering::Relaxed);
    let did_finish = finished.load(Ordering::Relaxed);

    if !did_finish {
        eprintln!(
            "  CONFIRMED BUG: Deadlock detected! Only {} of 400 annotations sent before blocking.",
            sent
        );
        eprintln!("  Root cause: Event::AnnotationAdded uses blocking evt_tx.send()");
        eprintln!("  Fix: Use try_send_event() for AnnotationAdded, like high-frequency events");
    } else {
        eprintln!(
            "  Sent all {} annotations without deadlock (bug may be fixed)",
            sent
        );
    }

    // To cleanly shut down, we MUST drain the event channel first.
    // Otherwise the processing thread stays blocked on evt_tx.send() and
    // session.shutdown() will hang forever trying to join it.
    let stop_drain = Arc::new(AtomicBool::new(false));
    let (drain_handle, _) = spawn_event_drainer(event_rx, Arc::clone(&stop_drain));

    // Give the drainer a moment to unblock the processing thread
    std::thread::sleep(Duration::from_millis(200));

    // Now the sender thread should also unblock (commands can flow again)
    // Wait for it with a timeout
    let sender_deadline = Instant::now() + Duration::from_secs(3);
    loop {
        if finished.load(Ordering::Relaxed) || Instant::now() > sender_deadline {
            break;
        }
        std::thread::sleep(Duration::from_millis(50));
    }

    stop_drain.store(true, Ordering::Relaxed);
    session.shutdown();
    drain_handle.join().ok();
    sender_thread.join().ok();

    std::fs::remove_file(&path).ok();

    // This test documents the bug. We expect deadlock (sent < 400).
    // When the bug is fixed, all 400 should send successfully.
    if !did_finish {
        eprintln!(
            "  TEST RESULT: BUG CONFIRMED (deadlock at annotation {})",
            sent
        );
    } else {
        eprintln!("  TEST RESULT: No deadlock detected");
    }
}

// ============================================================================
// Test 14: Concurrent analysis + decoder + recording
// ============================================================================

#[test]
fn stress_concurrent_everything() {
    eprintln!("\n=== Test 14: Concurrent analysis + decoder + recording ===");
    let sample_rate = 2_048_000.0;
    let (path, _) = generate_test_cf32("concurrent", sample_rate, 3.0);

    let device = ReplayDevice::open(&path, sample_rate).expect("open replay device");
    let config = make_config(sample_rate, 4096);

    let (session, event_rx) =
        SessionManager::new_with_device(config, device, full_registry()).expect("start session");

    // Drain concurrently (AnalysisResult, Status use blocking send)
    let stop = Arc::new(AtomicBool::new(false));
    let (drainer, drainer_stats) = spawn_event_drainer(event_rx, Arc::clone(&stop));

    // Enable a bunch of decoders
    session
        .send(Command::EnableDecoder("pocsag".to_string()))
        .ok();
    session
        .send(Command::EnableDecoder("adsb".to_string()))
        .ok();
    session
        .send(Command::EnableDecoder("aprs".to_string()))
        .ok();
    session.send(Command::EnableDecoder("ais".to_string())).ok();
    session.send(Command::EnableDecoder("ook".to_string())).ok();

    // Start tracking
    session.send(Command::StartTracking).ok();

    // Start recording
    let rec_path = PathBuf::from(format!(
        "/tmp/waverunner_stress_conc_{}.cf32",
        std::process::id()
    ));
    session
        .send(Command::StartRecord {
            path: rec_path.clone(),
            format: RecordFormat::RawCf32,
        })
        .ok();

    // Capture reference
    session.send(Command::CaptureReference).ok();

    // Spam analysis while everything else is running
    for i in 0..50u64 {
        let _ = session.send(Command::RunAnalysis {
            id: i,
            request: match i % 4 {
                0 => {
                    analysis::AnalysisRequest::MeasureSignal(analysis::measurement::MeasureConfig {
                        signal_center_bin: 2048,
                        signal_width_bins: 400,
                        adjacent_width_bins: 200,
                        obw_threshold_db: 26.0,
                    })
                }
                1 => analysis::AnalysisRequest::AnalyzeBurst(analysis::burst::BurstConfig {
                    threshold_db: 6.0,
                    min_burst_samples: 100,
                    sample_rate,
                }),
                2 => analysis::AnalysisRequest::EstimateModulation(
                    analysis::modulation::ModulationConfig {
                        sample_rate,
                        fft_size: 2048,
                    },
                ),
                _ => analysis::AnalysisRequest::CompareSpectra,
            },
        });
    }

    // Tune while all this is happening
    for i in 0..20u64 {
        let _ = session.send(Command::Tune(88e6 + i as f64 * 2e6));
    }

    // Stop recording
    let _ = session.send(Command::StopRecord);

    let deadline = Instant::now() + Duration::from_secs(15);
    while session.is_running() && Instant::now() < deadline {
        std::thread::sleep(Duration::from_millis(100));
    }

    stop.store(true, Ordering::Relaxed);
    session.shutdown();
    drainer.join().expect("drainer panicked");
    std::fs::remove_file(&path).ok();
    std::fs::remove_file(&rec_path).ok();
    let mut sidecar = rec_path.clone();
    sidecar.set_extension("sigmf-meta");
    std::fs::remove_file(&sidecar).ok();

    let stats = drainer_stats.lock().unwrap().clone();
    if let Some(stats) = stats {
        eprintln!(
            "  blocks_processed={}, blocks_dropped={}, events_dropped={}",
            stats.blocks_processed, stats.blocks_dropped, stats.events_dropped
        );
    }
    eprintln!("  PASSED: Concurrent everything without panic");
}

// ============================================================================
// Test 15: Duplicate decoder enable (should be idempotent)
// ============================================================================

#[test]
fn stress_duplicate_decoder_enable() {
    eprintln!("\n=== Test 15: Duplicate decoder enable (idempotency) ===");
    let sample_rate = 2_048_000.0;
    let (path, _) = generate_test_cf32("dupdec", sample_rate, 1.5);

    let device = ReplayDevice::open(&path, sample_rate).expect("open replay device");
    let config = make_config(sample_rate, 2048);

    let (session, event_rx) =
        SessionManager::new_with_device(config, device, full_registry()).expect("start session");

    // Drain concurrently (DecoderEnabled status events use blocking send)
    let stop = Arc::new(AtomicBool::new(false));
    let (drainer, drainer_stats) = spawn_event_drainer(event_rx, Arc::clone(&stop));

    // Enable same decoder 100 times
    for _ in 0..100 {
        let _ = session.send(Command::EnableDecoder("pocsag".to_string()));
    }

    // Disable it 100 times
    for _ in 0..100 {
        let _ = session.send(Command::DisableDecoder("pocsag".to_string()));
    }

    // Enable nonexistent decoder
    for _ in 0..50 {
        let _ = session.send(Command::EnableDecoder(
            "nonexistent-decoder-xyz".to_string(),
        ));
    }

    let deadline = Instant::now() + Duration::from_secs(10);
    while session.is_running() && Instant::now() < deadline {
        std::thread::sleep(Duration::from_millis(100));
    }

    stop.store(true, Ordering::Relaxed);
    session.shutdown();
    drainer.join().expect("drainer panicked");
    std::fs::remove_file(&path).ok();

    let stats = drainer_stats.lock().unwrap().clone();
    if let Some(stats) = stats {
        eprintln!("  blocks_processed={}", stats.blocks_processed);
    }
    eprintln!("  PASSED: Duplicate enable/disable without panic");
}

// ============================================================================
// Test 16: Shutdown during active processing
// ============================================================================

#[test]
fn stress_shutdown_during_processing() {
    eprintln!("\n=== Test 16: Shutdown during active processing ===");
    let sample_rate = 2_048_000.0;
    let (path, _) = generate_test_cf32("shutproc", sample_rate, 5.0);

    for trial in 0..10u64 {
        let device = ReplayDevice::open(&path, sample_rate).expect("open replay device");
        let config = make_config(sample_rate, 2048);

        let (session, _event_rx) = SessionManager::new_with_device(config, device, full_registry())
            .expect("start session");

        // Enable decoders
        session
            .send(Command::EnableDecoder("pocsag".to_string()))
            .ok();
        session
            .send(Command::EnableDecoder("adsb".to_string()))
            .ok();
        session.send(Command::StartTracking).ok();

        // Varying delays before shutdown
        let delay_ms = trial * 10 + 5;
        std::thread::sleep(Duration::from_millis(delay_ms));

        // Abrupt shutdown while everything is running
        session.shutdown();

        if trial % 3 == 0 {
            eprintln!("  Trial {}/10 (delay={}ms) OK", trial + 1, delay_ms);
        }
    }

    std::fs::remove_file(&path).ok();
    eprintln!("  PASSED: 10 shutdown-during-processing cycles without deadlock");
}

// ============================================================================
// Test 17: Sample rate switching under load
// ============================================================================

#[test]
fn stress_sample_rate_switching() {
    eprintln!("\n=== Test 17: Sample rate switching under load ===");
    let sample_rate = 2_048_000.0;
    let (path, _) = generate_test_cf32("rateswitch", sample_rate, 3.0);

    let device = ReplayDevice::open(&path, sample_rate).expect("open replay device");
    let config = make_config(sample_rate, 2048);

    let (session, event_rx) =
        SessionManager::new_with_device(config, device, full_registry()).expect("start session");

    // Drain concurrently
    let stop = Arc::new(AtomicBool::new(false));
    let (drainer, drainer_stats) = spawn_event_drainer(event_rx, Arc::clone(&stop));

    session
        .send(Command::EnableDecoder("pocsag".to_string()))
        .ok();
    session.send(Command::StartTracking).ok();

    // Rapidly switch sample rates
    let rates = [
        1_024_000.0,
        2_048_000.0,
        2_400_000.0,
        1_024_000.0,
        3_200_000.0,
        2_048_000.0,
    ];
    for cycle in 0..10 {
        for &rate in &rates {
            let _ = session.send(Command::SetSampleRate(rate));
        }
        if cycle % 3 == 0 {
            eprintln!("  Rate switch cycle {}/10", cycle + 1);
        }
    }

    let deadline = Instant::now() + Duration::from_secs(15);
    while session.is_running() && Instant::now() < deadline {
        std::thread::sleep(Duration::from_millis(100));
    }

    stop.store(true, Ordering::Relaxed);
    session.shutdown();
    drainer.join().expect("drainer panicked");
    std::fs::remove_file(&path).ok();

    let stats = drainer_stats.lock().unwrap().clone();
    if let Some(stats) = stats {
        eprintln!(
            "  blocks_processed={}, blocks_dropped={}",
            stats.blocks_processed, stats.blocks_dropped
        );
    }
    eprintln!("  PASSED: Sample rate switching without panic");
}
